### ISSUE TITLE
There is the hardcoded vendor path in Varien_Autoload class

### ISSUE THREAD

**Issue by andkirby** [ajbonner/magento-composer-autoload#4]
It's a blocker to use the vendor directory by some different path.

**Comment by ajbonner** [comment]
Yeah this is a known 'issue', the offending code is at https://github.com/ajbonner/magento-composer-autoload/blob/master/app/code/community/Varien/Autoload.php#L65

Any suggestions for a reliable fix?

We could use a define or something like that to get around it. Or we could read in composer.json and look for vendor-dir. 

It was never clear to me a straight forward performant way to solve this so in the absence of any complaints I left it as is.

**Comment by andkirby** [comment]
I suppose it could be done plugin.
Or, make some "post-install" script which could replace a default path.

**Comment by ajbonner** [comment]
The cleanest ways I can think of 

- Look for the presence of a config file in app/etc/local, read it and cache the results. Use this to control autoloading

- Use environment variables to override the vendor path/directory name, for example, COMPOSER_VENDORDIR=plugins php index.php, or in nginx set up a fastcgi_param

`
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_pass   unix:/var/run/php5-fpm.sock;
            fastcgi_param  MAGE_RUN_CODE default;
            fastcgi_param  MAGE_RUN_TYPE store;
            fastcgi_param  MAGE_IS_DEVELOPER_MODE 1;
            fastcgi_param  MAGE_COMPOSER_VENDORDIR plugins;
            include fastcgi_params;
        }
`

**Comment by andkirby** [comment]
Hm, it could be an option.
But it would be great if it will be set during the module installation.
